// @generated by governance/scripts/generate_sdk.py
// DO NOT EDIT MANUALLY. Run 'python3 governance/scripts/generate_sdk.py' to update.

// Top-level domains/areas
export enum GovernanceScope {
  INGRESS = 'INGRESS',
  CORE = 'CORE',
  IAM = 'IAM',
  BILLING = 'BILLING',
  TENANT = 'TENANT',
  LLM = 'LLM',
  RAG = 'RAG',
  EVENT = 'EVENT',
  OBS = 'OBS',
  SEC = 'SEC',
  SUPPLY = 'SUPPLY',
  API = 'API',
  CLIENT = 'CLIENT',
}

// Official Telemetry Prefixes
export enum TelemetryPrefix {
  OTEL = 'OTEL',
  SRE = 'SRE',
  SEC = 'SEC',
  DATA = 'DATA',
  BIZ = 'BIZ',
  AI = 'AI',
  UX = 'UX',
}

// Standardized Metrics
export enum MetricType {
  CITATION_DOCS = 'CITATION_DOCS',
  COST_USD = 'COST_USD',
  CPU_USAGE = 'CPU_USAGE',
  DLQ_COUNT = 'DLQ_COUNT',
  ERROR_COUNT = 'ERROR_COUNT',
  ERROR_PERCENT = 'ERROR_PERCENT',
  LATENCY_P50 = 'LATENCY_P50',
  LATENCY_P99 = 'LATENCY_P99',
  MEM_USAGE = 'MEM_USAGE',
  QUEUE_SIZE = 'QUEUE_SIZE',
  TOKENS_IN = 'TOKENS_IN',
  TOKENS_OUT = 'TOKENS_OUT',
}

// Standardized Descriptors (Logs/Events)
export enum EventDescriptor {
  ACL_DENY = 'ACL_DENY',
  AVAILABILITY = 'AVAILABILITY',
  CACHE_HIT = 'CACHE_HIT',
  CACHE_MISS = 'CACHE_MISS',
  COST = 'COST',
  DB_CONN = 'DB_CONN',
  ERROR_RATE = 'ERROR_RATE',
  HALLUCINATION_RATE = 'HALLUCINATION_RATE',
  JITTER = 'JITTER',
  LAG = 'LAG',
  LATENCY = 'LATENCY',
  LOGIN_FAIL = 'LOGIN_FAIL',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  MFA_CHALLENGE = 'MFA_CHALLENGE',
  ORDER_TOTAL = 'ORDER_TOTAL',
  PACKET_LOSS = 'PACKET_LOSS',
  QUEUE_DEPTH = 'QUEUE_DEPTH',
  RELEVANCE_SCORE = 'RELEVANCE_SCORE',
  SATURATION = 'SATURATION',
  SUB_STATUS = 'SUB_STATUS',
  THROUGHPUT = 'THROUGHPUT',
  TOKEN_COUNT = 'TOKEN_COUNT',
  TOXICITY_SCORE = 'TOXICITY_SCORE',
}

// Validation Constants
export const VALID_SCOPES = Object.values(GovernanceScope);
export const VALID_PREFIXES = Object.values(TelemetryPrefix);

// Strict Telemetry Event Structure
export interface TelemetryEvent {
  prefix: TelemetryPrefix;
  scope: GovernanceScope;
  descriptor: EventDescriptor;
  value?: number;
  unit?: string;
  context?: Record<string, unknown>;
}

// Runtime Validator
export function validateEvent(event: TelemetryEvent): boolean {
  return (
    VALID_PREFIXES.includes(event.prefix) &&
    VALID_SCOPES.includes(event.scope)
  );
}