import csv
import os
from pathlib import Path

# Paths
base_dir = Path("governance")
definitions_dir = base_dir / "definitions"
src_lib_dir = Path("src/lib")
src_lib_dir.mkdir(parents=True, exist_ok=True)
output_file = src_lib_dir / "governance.ts"

def read_csv(filename):
    filepath = definitions_dir / filename
    if not filepath.exists():
        print(f"Warning: {filename} not found.")
        return []
    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        return list(reader)

def generate_sdk():
    print("Generating Governance SDK...")
    
    # 1. Read Data
    official_prefixes = read_csv("OfficialPrefixRegistry.csv")
    signals = read_csv("SignalCatalog.csv")
    roots = read_csv("RootNamespaceMap.csv")
    descriptors = read_csv("DescriptorCatalog.csv")

    # 2. Build Content
    lines = []
    lines.append("// @generated by governance/scripts/generate_sdk.py")
    lines.append("// DO NOT EDIT MANUALLY. Run 'python3 governance/scripts/generate_sdk.py' to update.")
    lines.append("")

    # --- GovernanceScope Enum ---
    lines.append("// Top-level domains/areas")
    lines.append("export enum GovernanceScope {")
    for row in roots:
        token = row['root_token']
        # Sanitize mostly upper case
        lines.append(f"  {token} = '{token}',")
    lines.append("}")
    lines.append("")

    # --- LogPrefix Enum ---
    lines.append("// Official Telemetry Prefixes")
    lines.append("export enum TelemetryPrefix {")
    for row in official_prefixes:
        prefix = row['prefix']
        lines.append(f"  {prefix} = '{prefix}',")
    lines.append("}")
    lines.append("")

    # --- MetricType Enum (Signals) ---
    lines.append("// Standardized Metrics")
    lines.append("export enum MetricType {")
    unique_signals = sorted(list(set(row['signal_name'] for row in signals)))
    for sig in unique_signals:
        lines.append(f"  {sig} = '{sig}',")
    lines.append("}")
    lines.append("")

    # --- Descriptor Enum ---
    lines.append("// Standardized Descriptors (Logs/Events)")
    lines.append("export enum EventDescriptor {")
    unique_descriptors = sorted(list(set(row['descriptor_token'] for row in descriptors)))
    for desc in unique_descriptors:
        lines.append(f"  {desc} = '{desc}',")
    lines.append("}")
    lines.append("")

    # --- Constants & Helper Types ---
    lines.append("// Validation Constants")
    lines.append("export const VALID_SCOPES = Object.values(GovernanceScope);")
    lines.append("export const VALID_PREFIXES = Object.values(TelemetryPrefix);")
    lines.append("")
    
    # --- Interface for Strict Typing ---
    lines.append("// Strict Telemetry Event Structure")
    lines.append("export interface TelemetryEvent {")
    lines.append("  prefix: TelemetryPrefix;")
    lines.append("  scope: GovernanceScope;")
    lines.append("  descriptor: EventDescriptor;")
    lines.append("  value?: number;")
    lines.append("  unit?: string;")
    lines.append("  context?: Record<string, unknown>;")
    lines.append("}")

    # --- Validator Function ---
    lines.append("")
    lines.append("// Runtime Validator")
    lines.append("export function validateEvent(event: TelemetryEvent): boolean {")
    lines.append("  return (")
    lines.append("    VALID_PREFIXES.includes(event.prefix) &&")
    lines.append("    VALID_SCOPES.includes(event.scope)")
    lines.append("  );")
    lines.append("}")

    # 3. Write File
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))
    
    print(f"Successfully generated {output_file}")

if __name__ == "__main__":
    generate_sdk()
